import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'Change App Language': 'Change App Language',
      'SIGN IN': 'SIGN IN',
       'OR':'OR',
      'SIGN UP': 'SIGN UP',
      'LOGIN': 'LOGIN',
      ' LOGIN': ' LOGIN',
      " SIGN UP": ' SIGN UP',
      'Signup': 'Signup',
      'Please signup to continue': 'Please signup to continue',
      'Add Profile Picture': 'Add Profile Picture',
      'Full Name': 'Full Name',
      'Your name': 'Your name',
      'Type a password': 'Type a password',
      'Email': 'Email',
      'Password': 'Password',
      'Your email': 'Your email',
      'Create Password': 'Create password',
      'Type a strong password': 'Type a strong password',
      'Phone Number': 'Phone Number',
      'Customer Login': 'Customer Login',
      'Please Login to continue': 'Please Login to continue',
      'Forgot Password?': 'Forgot Password?',
      "Do not Have an Account? ": 'Don’t have any account?',
      'Already Have an Account? ':'Already Have an Account?',
      'Home': 'Home',
      'My Orders': 'My Orders',
      'Order History': 'Order History',
      'Notifications': 'Notifications',
      'Help & Support': 'Help & Support',
      'Language': 'Language',
      'English': 'English',
      'Mongolian': 'Mongolian',
      'Logout': 'Logout',
      'Ok': 'Ok',
      'No Orders Found': 'No Orders Found',
      'Cancel': 'Cancel',
      'POPULAR DELIVERIES': 'POPULAR DELIVERIES',
      'SCHEDULE A NEW \n DELIVERY': 'SCHEDULE A NEW \n DELIVERY',
      'Do you want to Logout?': 'Do you want to Logout?',
      'SUBMIT': 'SUBMIT',
      'Describe your Issue here': 'Describe your Issue here',
      'Report an issue': 'Report an issue',
      'Enter your Order Id here': 'Enter your Order Id here',
      'Order ID': 'Order ID',
      'No Notifications Found': 'No Notifications Found',
      'Please How we can help you?': 'Please How we can help you?',
      'Help And Support': 'Help And Support',
      'Select your Issue': 'Select your Issue',
      'Issue Regarding Product Damage': 'Issue Regarding Product Damage',
      'Product Misplace': 'Product Misplace',
      'Late Delivery': 'Late Delivery',
      'Bad user experience': 'Bad user experience',
      'LOGOUT': 'LOGOUT',
      'Address': 'Address',
      'EDIT PROFILE': 'EDIT PROFILE',
      'Profile': 'Profile',
      'COMPLETE': 'COMPLETE',
      'CANCEL': 'CANCEL',

    },
    'mn_MN': {
      'Change App Language': 'Програмын хэлийг өөрчлөх',
      'SIGN IN': 'НЭВТРҮҮЛЭХ',
       'OR':'ЭСВЭЛ',
      'No Orders Found': 'Захиалга олдсонгүй',
      " SIGN UP": ' БҮРТГҮҮЛЭХ',
      'SIGN UP': 'БҮРТГҮҮЛЭХ',
      'Signup': 'Бүртгүүлэх',
      'LOGIN': 'НЭВТРЭХ',
      ' LOGIN': ' НЭВТРЭХ',
      'Please signup to continue': 'Үргэлжлүүлэхийн тулд бүртгүүлнэ үү',
      'Add Profile Picture': 'Профайл зураг нэмэх',
      'Full Name': 'Бүтэн нэр',
      'Your name': 'Таны нэр',
      'Email': 'Имэйл',
      'Notifications': 'Мэдэгдэл',
      'Password': 'Нууц үг',
      'Your email': 'Таны имэйл',
      'No Notifications Found': 'Мэдэгдэл олдсонгүй',
      'Create Password': 'Шинэ нууц үг үүсгэх',
      'Type a strong password': 'Хүчтэй нууц үг оруулна уу',
      'Type a password': 'Нууц үг оруулна уу',
      'Phone Number': 'Утасны дугаар',
      'Customer Login': 'Хэрэглэгчийн нэвтрэх',
      'Please Login to continue': 'Үргэлжлүүлэхийн тулд нэвтэрнэ үү',
      'Forgot Password?': 'Нууц үгээ мартсан уу?',
      "Do not Have an Account? ": 'Ямар ч данс байхгүй юу?',
      'Already Have an Account? ':'Бүртгэлтэй юу?',
      'Home': 'Гэр',
      'My Orders': 'Миний захиалга',
      'Order History': 'Захиалгын түүх',
      'Help & Support': 'Тусламж ба дэмжлэг',
      'Language': 'Хэл',
      'English': 'Англи',
      'Mongolian': 'Монгол',
      'Logout': 'Гарах',
      'Ok': 'Болж байна уу',
      'Cancel': 'Цуцлах',
      'Do you want to Logout?': 'Та гарахыг хүсэж байна уу?',
      'POPULAR DELIVERIES': 'АЛДАРТАЙ хүргэлт',
      'SCHEDULE A NEW \n DELIVERY': 'ШИНЭ \n ХҮРГЭЛТИЙН ТӨЛӨВЛӨГӨӨ',
      'SUBMIT': 'ИЛГЭЭХ',
      'Describe your Issue here': 'Асуудлаа энд тайлбарлана уу',
      'Report an issue': 'Асуудлыг мэдээлэх',
      'Enter your Order Id here': 'Захиалгын дугаараа энд оруулна уу',
      'Order ID': 'Захиалгын ID',
      'Please How we can help you?': 'Бид танд хэрхэн туслах вэ?',
      'Help And Support': 'Тусламж ба дэмжлэг',
      'Select your Issue': 'Асуудлаа сонгоно уу',
      'Issue Regarding Product Damage': 'Бүтээгдэхүүний гэмтэлтэй холбоотой асуудал',
      'Product Misplace': 'Бүтээгдэхүүний буруу газар',
      'Late Delivery': 'Хожуу хүргэлт',
      'Bad user experience': 'Хэрэглэгчийн муу туршлага',
      'LOGOUT': 'ГАРАХ',
      'Address': 'Хаяг',
      'EDIT PROFILE': 'засварлах Хувийн мэдээллийг',
      'Profile': 'Профайл',
      'COMPLETE': 'БҮРЭН БАЙНА',
      'CANCEL': 'Цуцлах',
    }
  };
}