import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'Change App Language': 'Change App Language',
      'SIGN IN': 'SIGN IN',
       'OR':'OR',
      'SIGN UP': 'SIGN UP',
      'LOGIN': 'LOGIN',
      ' LOGIN': ' LOGIN',
      " SIGN UP": ' SIGN UP',
      'Signup': 'Signup',
      'Please signup to continue': 'Please signup to continue',
      'Add Profile Picture': 'Add Profile Picture',
      'Full Name': 'Full Name',
      'Your name': 'Your name',
      'Type a password': 'Type a password',
      'Email': 'Email',
      'Password': 'Password',
      'Your email': 'Your email',
      'Create Password': 'Create password',
      'Type a strong password': 'Type a strong password',
      'Phone Number': 'Phone Number',
      'Customer Login': 'Customer Login',
      'Please Login to continue': 'Please Login to continue',
      'Forgot Password?': 'Forgot Password?',
      "Do not Have an Account? ": 'Don’t have any account?',
      'Already Have an Account? ':'Already Have an Account?',
      'Home': 'Home',
      'My Orders': 'My Orders',
      'Order History': 'Order History',
      'Notifications': 'Notifications',
      'Help & Support': 'Help & Support',
      'Language': 'Language',
      'English': 'English',
      'Mongolian': 'Mongolian',
      'Logout': 'Logout',
      'Ok': 'Ok',
      'No Orders Found': 'No Orders Found',
      'Cancel': 'Cancel',
      'POPULAR DELIVERIES': 'POPULAR DELIVERIES',
      'SCHEDULE A NEW \n DELIVERY': 'SCHEDULE A NEW \n DELIVERY',
      'Do you want to Logout?': 'Do you want to Logout?',
      'SUBMIT': 'SUBMIT',
      'Payment Complete': 'Payment Complete',
      'Your Tracking ID': 'Your Tracking ID',
      'Describe your Issue here': 'Describe your Issue here',
      'Report an issue': 'Report an issue',
      'Enter your Order Id here': 'Enter your Order Id here',
      'Order ID': 'Order ID',
      'No Notifications Found': 'No Notifications Found',
      'Please How we can help you?': 'Please How we can help you?',
      'Help And Support': 'Help And Support',
      'Select your Issue': 'Select your Issue',
      'Issue Regarding Product Damage': 'Issue Regarding Product Damage',
      'Product Misplace': 'Product Misplace',
      'Late Delivery': 'Late Delivery',
      'Bad user experience': 'Bad user experience',

      'LOGOUT': 'LOGOUT',
      'Address': 'Address',
      'EDIT PROFILE': 'EDIT PROFILE',
      'Profile': 'Profile',
      'COMPLETE': 'COMPLETE',
      'CANCEL': 'CANCEL',
      'CREATE A DELIVERY TASK': 'CREATE A DELIVERY TASK',
      'PICK-UP DETAILS': 'PICK-UP DETAILS',
      'DELIVERY DETAILS': 'DELIVERY DETAILS',
      'SCHEDULE ORDER': 'SCHEDULE ORDER',
      'RIGHT AWAY': 'RIGHT AWAY',
      'SCHEDULE FOR LATER': 'SCHEDULE FOR LATER',
      'SELECT TIME & DATE': 'SELECT TIME & DATE',
      'Current Date/Time': 'Current Date/Time',
      'SELECT VEHICLE': 'SELECT VEHICLE',
      'CHOOSE PARCEL VALUE': 'CHOOSE PARCEL VALUE',
      'UP TO 100000 MNT': 'UP TO 100000 MNT',
      'BETWEEN 100k & 500k MNT': 'BETWEEN 100k & 500k MNT',
      'BETWEEN 500k & 1 MILLION MNT': 'BETWEEN 500k & 1 MILLION MNT',
      'Prohibited & illegal item does not \ninclude in this parcel': 'Prohibited & illegal item does not \ninclude in this parcel',
      'CONFIRM BOOKING': 'CONFIRM BOOKING',
      'LOOKING FOR DRIVER': 'LOOKING FOR DRIVER',
      'CAR': 'CAR',
      'MINI TRUCK': 'MINI TRUCK',
      'BIKE': 'BIKE',
      'SCOOTER': 'SCOOTER',
      'TRUCK': 'TRUCK',
      'VAN': 'VAN',
      'Save': 'Save',
      'Delivery Price Offer': 'Delivery Price Offer',
      'Parcel Description': 'Parcel Description',
      'Parcel Weight': 'Parcel Weight',
      'Parcel Name': 'Parcel Name',
      'Enter Email': 'Enter Email',
      'Enter Phone Number': 'Enter Phone Number',
      'Enter Name': 'Enter Name',
      'Name': 'Name',
      'Select date ': 'Select date ',
      'Select Time ': 'Select Time ',
      'Select Pickup Address': 'Select Pickup Address',
      'Select Delivery Address': 'Select Delivery Address',
      'TRACK YOUR ORDER': 'TRACK YOUR ORDER',
      'How’s Your Order?  Feedback Please': 'How’s Your Order?  Feedback Please',
      'SEND FEEDBACK': 'SEND FEEDBACK',

      'Profile Picture is required':'Profile Picture is required',
      'Full Name is required':'Full Name is required',
      'Email is required':'Email is required',
      'Enter a valid email!':'Enter a valid email!',
      'Password is required':'Password is required',
      'Password should be at least six digits.':'Password should be at least six digits.',
      'Phone number is required': 'Phone number is required',

      'PROCEED TO PAY': 'PROCEED TO PAY',
      'ADD PROMO / GIFT CODE': 'ADD PROMO / GIFT CODE',
      'Q PAY': 'Q PAY',
      'Time': 'Time',
      'Distance': 'Distance',
      'Price Order': 'Price Order',
      'Weight': 'Weight',
      'ORDER SUMMARY': 'ORDER SUMMARY',
      'PAY': 'PAY',
      'Card Holder': 'Card Holder',
      'CVV': 'CVV',
      'Expiry Date': 'Expiry Date',
      'Number': 'Number',
      'PAYMENT': 'PAYMENT',
      'Waiting For Acceptance': 'Waiting For Acceptance',
      'accept your Request': 'accept your Request',
      'Waiting for Pickup': 'Waiting for Pickup',
      'Parcel Picked up': 'Parcel Picked up',
      'Delivered Location': 'Delivered Location',
      'TRACK ORDER': 'TRACK ORDER',
      'ORDER COMPLETE': 'ORDER COMPLETE',
      'YOUR DRIVER WILL ARRIVE IN': 'YOUR DRIVER WILL ARRIVE IN',
      'Order Cancel': 'Order Cancel',
      'Cancel Order': 'Cancel Order',
      'Are you sure you want to cancel order?': 'Are you sure you want to cancel order?',
      'Yes': 'Yes',
      'Success': 'Success',
      'Report Sent Successfully!': 'Report Sent Successfully!',
      'Error': 'Error',
      'Your email address is invalid': 'Your email address is invalid',
      'Your password is wrong.': 'Your password is wrong.',
      'User with this email does not exist.': 'User with this email does not exist.',
      'User with this email has been disabled': 'User with this email has been disabled',
      'Too many requests': 'Too many requests',
      'Signing in with Email and Password is not enabled.': 'Signing in with Email and Password is not enabled.',
      'An undefined Error happened': 'An undefined Error happened',
      "Email already exist, kindly try some one else":"Email already exist, kindly try some one else",
      'Account Created Successfully!!': 'Account Created Successfully!!',
      'Feedback Sent Successfully!': 'Feedback Sent Successfully!',
      'Please enter orderId': 'Please enter orderId',
      'Please add rating': 'Please add rating',
      'Logged Out Successfully': 'Logged Out Successfully',
      'Payment Successful': 'Payment Successful',
      'Invalid Card Details': 'Invalid Card Details',
      'Order Delivered Successfully': 'Order Delivered Successfully',
      'Required': 'Required',
      'Please save delivery details': 'Please save delivery details',
      'Pickup Delivery Description is required': 'Pickup Delivery Description is required',
      'Delivery Email is required': 'Delivery Email is required',
      'Delivery Phone is required': 'Delivery Phone is required',
      'Delivery Name is required': 'Delivery Name is required',
      'Delivery Address is required': 'Delivery Address is required',
      'Pickup Delivery Price Offer is required': 'Pickup Delivery Price Offer is required',
      'Pickup Parcel Description is required': 'Pickup Parcel Description is required',
      'Pickup Parcel Weight is required': 'Pickup Parcel Weight is required',
      'Pickup Parcel Name is required': 'Pickup Parcel Name is required',
      'Pickup Email is required': 'Pickup Email is required',
      'Pickup Phone is required': 'Pickup Phone is required',
      'Pickup Name is required': 'Pickup Name is required',
      'Pickup Address is required': 'Pickup Address is required',


    },
    'mn_MN': {
      'Profile Picture is required':'Профайл зураг шаардлагатай',
      'Full Name is required':'Бүтэн нэр оруулах шаардлагатай',
      'Email is required':'Имэйл шаардлагатай',
      'Enter a valid email!':'EХүчинтэй имэйл оруулна уу!',
      'Password is required':'нууц үг шаардлагатай',
      'Password should be at least six digits.':'Нууц үг дор хаяж зургаан оронтой байх ёстой.',
      'Phone number is required': 'Утасны дугаар шаардлагатай',
      'Payment Complete': 'Төлбөр дууссан',
      'Your Tracking ID': 'Таны мөрдөх ID',

      'Change App Language': 'Програмын хэлийг өөрчлөх',
      'SIGN IN': 'НЭВТРҮҮЛЭХ',
       'OR':'ЭСВЭЛ',
      'No Orders Found': 'Захиалга олдсонгүй',
      " SIGN UP": ' БҮРТГҮҮЛЭХ',
      'SIGN UP': 'БҮРТГҮҮЛЭХ',
      'Signup': 'Бүртгүүлэх',
      'LOGIN': 'НЭВТРЭХ',
      ' LOGIN': ' НЭВТРЭХ',
      'Please signup to continue': 'Үргэлжлүүлэхийн тулд бүртгүүлнэ үү',
      'Add Profile Picture': 'Профайл зураг нэмэх',
      'Full Name': 'Бүтэн нэр',
      'Your name': 'Таны нэр',
      'Email': 'Имэйл',
      'Notifications': 'Мэдэгдэл',
      'Password': 'Нууц үг',
      'Your email': 'Таны имэйл',
      'No Notifications Found': 'Мэдэгдэл олдсонгүй',
      'Create Password': 'Шинэ нууц үг үүсгэх',
      'Type a strong password': 'Хүчтэй нууц үг оруулна уу',
      'Type a password': 'Нууц үг оруулна уу',
      'Phone Number': 'Утасны дугаар',
      'Customer Login': 'Хэрэглэгчийн нэвтрэх',
      'Please Login to continue': 'Үргэлжлүүлэхийн тулд нэвтэрнэ үү',
      'Forgot Password?': 'Нууц үгээ мартсан уу?',
      "Do not Have an Account? ": 'Ямар ч данс байхгүй юу?',
      'Already Have an Account? ':'Бүртгэлтэй юу?',
      'Home': 'Гэр',
      'My Orders': 'Миний захиалга',
      'Order History': 'Захиалгын түүх',
      'Help & Support': 'Тусламж ба дэмжлэг',
      'Language': 'Хэл',
      'English': 'Англи',
      'Mongolian': 'Монгол',
      'Logout': 'Гарах',
      'Ok': 'Болж байна уу',
      'Cancel': 'Цуцлах',
      'ORDER COMPLETE': 'ЗАХИАЛГА БҮРЭН БАЙНА',
      'Do you want to Logout?': 'Та гарахыг хүсэж байна уу?',
      'POPULAR DELIVERIES': 'АЛДАРТАЙ хүргэлт',
      'SCHEDULE A NEW \n DELIVERY': 'ШИНЭ \n ХҮРГЭЛТИЙН ТӨЛӨВЛӨГӨӨ',

      'SUBMIT': 'ИЛГЭЭХ',
      'Describe your Issue here': 'Асуудлаа энд тайлбарлана уу',
      'Report an issue': 'Асуудлыг мэдээлэх',
      'Enter your Order Id here': 'Захиалгын дугаараа энд оруулна уу',
      'Order ID': 'Захиалгын ID',
      'Please How we can help you?': 'Бид танд хэрхэн туслах вэ?',
      'Help And Support': 'Тусламж ба дэмжлэг',
      'Select your Issue': 'Асуудлаа сонгоно уу',
      'Issue Regarding Product Damage': 'Бүтээгдэхүүний гэмтэлтэй холбоотой асуудал',
      'Product Misplace': 'Бүтээгдэхүүний буруу газар',
      'Late Delivery': 'Хожуу хүргэлт',
      'Bad user experience': 'Хэрэглэгчийн муу туршлага',

      'LOGOUT': 'ГАРАХ',
      'Address': 'Хаяг',
      'EDIT PROFILE': 'засварлах Хувийн мэдээллийг',
      'Profile': 'Профайл',
      'COMPLETE': 'БҮРЭН БАЙНА',
      'CANCEL': 'Цуцлах',
      'CREATE A DELIVERY TASK': 'ХҮРГЭЛТИЙН ДААЛГАВАР ҮҮСГЭЭРЭЙ',
      'PICK-UP DETAILS': 'АВАХ ДЭЛГЭРЭНГҮЙ',
      'DELIVERY DETAILS': 'ХҮРГЭЛТИЙН ДЭЛГЭРЭНГҮЙ',
      'SCHEDULE ORDER': 'ЗАХИАЛГЫН ХУВААРЬ',
      'RIGHT AWAY': 'ШУУД',
      'SCHEDULE FOR LATER': 'ДАРААХ ХУВААРЬ',
      'SELECT TIME & DATE': 'ЦАГ, ОГНОО СОНГОХ',
      'Current Date/Time': 'Одоогийн огноо/цаг',
      'SELECT VEHICLE': 'МАШИН СОНГО',
      'CHOOSE PARCEL VALUE': 'Илгээмжийн үнэ цэнийг сонго',
      'UP TO 100000 MNT': '100000 төгрөг хүртэл',
      'BETWEEN 100k & 500k MNT': '100 мянгаас 500 мянган төгрөгний хооронд',
      'BETWEEN 500k & 1 MILLION MNT': '500 мянгаас 1 САЯ ТӨГРӨГИЙН ХООРОНД',
      'Prohibited & illegal item does not \ninclude in this parcel': 'Хориотой & хууль бус зүйл энэ илгээмжид \n ороогүй болно',
      'CONFIRM BOOKING': 'ЗАХИАЛГАА БАТАЛГААРАЙ',
      'LOOKING FOR DRIVER': 'ЖОЛООЧ АЖИЛД БАЙНА',
      'CAR': 'МАШИН',
      'MINI TRUCK': 'МИНИ ачааны машин',
      'BIKE': 'ДУГУЙ',
      'SCOOTER': 'СКУТЕР',
      'TRUCK': 'Ачааны машин',
      'VAN': 'ВАН',
      'Save': 'Хадгалах',
      'Delivery Price Offer': 'Хүргэлтийн үнийн санал',
      'Parcel Description': 'Илгээмжийн тодорхойлолт',
      'Parcel Weight': 'Илгээмжийн жин',
      'Parcel Name': 'Илгээмжийн нэр',
      'Enter Email': 'Имэйл оруулна уу',
      'Enter Phone Number': 'Утасны дугаар оруулна уу',
      'Enter Name': 'Нэрийг оруулна уу',
      'Name': 'Нэр',
      'Select Pickup Address': 'Татаж авах хаягийг сонгоно уу',
      'Select Delivery Address': 'Хүргэлтийн хаягийг сонгоно уу',
      'Select date ': 'Огноог сонгоно уу ',
      'Select Time ': 'Цагийг сонгоно уу ',
      'TRACK YOUR ORDER': 'ЗАХИАЛГАА Хянаарай',
      'How’s Your Order?  Feedback Please': 'Таны захиалга ямар байна? Санал хүсэлт өгнө үү',
      'SEND FEEDBACK': 'САНАЛ ИЛГЭЭХ',

      'PROCEED TO PAY': 'ТӨЛБӨРИЙГ ҮРГЭЛЖЛҮҮЛ',
      'ADD PROMO / GIFT CODE': 'УРАМШУУЛАЛ / БЭЛГИЙН КОД НЭМЭХ',
      'Q PAY': 'Q PAY',
      'Time': 'Цаг хугацаа',
      'Distance': 'Зай',
      'Price Order': 'Үнийн захиалга',
      'Weight': 'Жин',
      'ORDER SUMMARY': 'ЗАХИАЛГЫН ХУРААНГУЙ',
      'PAY': 'ТӨЛБӨР',
      'Card Holder': 'Карт эзэмшигч',
      'CVV': 'CVV',
      'Expiry Date': 'Дуусах хугацаа',
      'Number': 'Тоо',
      'PAYMENT': 'ТӨЛБӨР',
      'Waiting For Acceptance': 'Хүлээн авахыг хүлээж байна',
      'accept your Request': 'Татаж авахыг хүлээж байна',
      'Waiting for Pickup': 'Татаж авахыг хүлээж байна',
      'Parcel Picked up': 'Илгээмж авсан',
      'Delivered Location': 'Хүргэгдсэн байршил',
      'TRACK ORDER': 'ЗАХИАЛГА ХЯНАХ',
      'YOUR DRIVER WILL ARRIVE IN': 'ТАНЫ ЖОЛООЧ ОРНО',
      'Order Cancel': 'Захиалга цуцлах',
      'Cancel Order': 'Захиалгыг цуцлах',
      'Are you sure you want to cancel order?': 'Та захиалгаа цуцлахдаа итгэлтэй байна уу?',
      'Yes': 'Тиймээ',
      'Success': 'Тиймээ',
      'Report Sent Successfully!': 'Тайланг амжилттай илгээлээ!',
      'Error': 'Алдаа',
      'Your email address is invalid': 'Таны имэйл хаяг буруу байна',
      'Your password is wrong.': 'Таны нууц үг буруу байна.',
      'User with this email does not exist.': 'Энэ имэйлтэй хэрэглэгч байхгүй байна.',
      'User with this email has been disabled': 'Энэ имэйлтэй хэрэглэгч идэвхгүй болсон',
      'Too many requests': 'Хэт олон хүсэлт',
      'Signing in with Email and Password is not enabled.': 'Имэйл болон нууц үгээр нэвтрэхийг идэвхжүүлээгүй байна.',
      'An undefined Error happened': 'Тодорхойгүй алдаа гарлаа',
      "Email already exist, kindly try some one else":"Имэйл аль хэдийн байгаа тул өөр хаягаар оролдоно уу",
      'Account Created Successfully!!': 'Бүртгэлийг амжилттай үүсгэсэн!!',
      'Feedback Sent Successfully!': 'Санал хүсэлтийг амжилттай илгээлээ!',
      'Please enter orderId': 'Захиалгын дугаар оруулна уу',
      'Please add rating': 'Үнэлгээ нэмнэ үү',
      'Logged Out Successfully': 'Амжилттай гарлаа',
      'Payment Successful': 'Төлбөр амжилттай боллоо',
      'Invalid Card Details': 'Хүчингүй картын мэдээлэл',
      'Order Delivered Successfully': 'Захиалгыг амжилттай хүргэлээ',
      'Required': 'Шаардлагатай',
      'Please save delivery details': 'Хүргэлтийн мэдээллийг хадгална уу',
      'Pickup Delivery Description is required': 'Хүргэлтийн тодорхойлолт шаардлагатай',
      'Delivery Email is required': 'Хүргэлтийн имэйл шаардлагатай',
      'Delivery Phone is required': 'Хүргэлтийн имэйл шаардлагатай',
      'Delivery Name is required': 'Хүргэлтийн нэр шаардлагатай',
      'Delivery Address is required': 'Хүргэлтийн хаяг шаардлагатай',
      'Pickup Delivery Price Offer is required': 'Хүргэлтийн үнийн саналыг авах шаардлагатай',
      'Pickup Parcel Description is required': 'Хүргэлтийн үнийн саналыг авах шаардлагатай',
      'Pickup Parcel Weight is required': 'Хүлээн авах илгээмжийн тодорхойлолт шаардлагатай',
      'Pickup Parcel Name is required': 'Хүлээн авах илгээмжийн нэр шаардлагатай',
      'Pickup Email is required': 'Хүлээн авах имэйл шаардлагатай',
      'Pickup Phone is required': 'Татаж авах утас шаардлагатай',
      'Pickup Name is required': 'Татаж авах нэр шаардлагатай',
      'Pickup Address is required': 'Татаж авах хаяг шаардлагатай',
    }
  };
}